### ISSUE TITLE
Typo in repository's description

### ISSUE THREAD

**Issue by Paul-Marie** [theo-mazars/ovh-bot#1]
Well, actually your repository's description is:
> Crawl OVH website to fin available dedicated server 

Didn't wanted ya to say `find` instead of `fin` ?

<details>
<summary>
</summary>

PS: I guess ya've some "missing `s`"'s issues :eyes:
</details>

**Comment by theo-mazars** [comment]
You're right, the readme was written a bit too fast, I'll fix this ASAP.
Thank you Paul for your feedback
